columns:
  longitude: float
  latitude: float
  housing_median_age: float
  total_rooms: float
  total_bedrooms: float
  population: float
  households: float
  median_income: float
  median_house_value: float
  ocean_proximity: category

numerical_columns:
  - longitude
  - latitude
  - housing_median_age
  - total_rooms
  - total_bedrooms
  - population
  - households
  - median_income



categorical_columns:
  - ocean_proximity




target_column: median_house_value

domain_value:
  ocean_proximity:
    - <1H OCEAN
    - INLAND
    - ISLAND
    - NEAR BAY
    - NEAR OCEAN



  



